[package]
name = "gpe"
version = "0.0.1"
authors = ["Will Crichton <willcrichton@cmu.edu>"]
build = "src/build.rs"

[profile.dev]
opt-level = 1
debug = true

[profile.release]
opt-level = 2

[dependencies.image]
git = "https://github.com/PistonDevelopers/image"